#!/bin/bash

# The 2D contour file
File='NACA.dat'

# Path to GMSH
chemin='/usr/bin/gmsh'

# Name given to the fluid-structure interface
Name_Surf='Aile'

# Extrusion length (in meter) | In 2D, this value corresponds to the length of the extruded section but there is only one cell in this direction
Envergure=0.14

# The chord of the NACA profiles available online is often 1. The parameter Ratio resizes the profile (homothety, center (0,0,0)) 
Ratio=0.08

# Position of the rotation center: X_c=X_r*chord ; Y_c=0 (from the trailing edge) - the rotation axis is assumed to be z
X_r=0.25 

# Angle of incidence
Rotation=15

# All the faces with z-coordinate < Fix will remain fix in the simulation (in 3D)
Fix=0

start=`date +%s`

# Taking back the mesh of the interface to mesh the solid with the same boundary faces. The mesh is composed of 2nd order finite elements (by default)
echo "Meshing the solid part with a perfect match with the solid structure at the interface"

python Recup_Aile.py $chemin $Name_Surf $Fix $Envergure $X_r $Rotation $File $Ratio

# GMSH fails to write aptly the INP file. The INP mesh is rewritten to be compatible with CalculiX
echo "Rewriting the inp mesh file to make it suitable for CalculiX"
python RewriteINP.py

# Housework
rm Maillage.geo Maillage.inp Maillage2.geo Maillage2.inp NACA.dat

end=`date +%s`
echo "Execution time: "$((end-start)) "s"

