#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=$(getApplication)

#runApplication cartesian2DMesh

#- Run serial
#runApplication $application
runApplication topoSet
runApplication createPatch -overwrite
#- Run parallel
runApplication decomposePar -cellDist
runParallel $application
runApplication reconstructPar

#runApplication postChannel

#------------------------------------------------------------------------------
